// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaTecnica_Backend.Data;

#nullable disable

namespace PruebaTecnica_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828012058_CreateUsers")]
    partial class CreateUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnica_Backend.Models.User", b =>
                {
                    b.Property<decimal>("UsuID")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("usuID");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UsuID");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            UsuID = 1m,
                            Apellido = "Pérez",
                            Nombre = "Juan"
                        },
                        new
                        {
                            UsuID = 2m,
                            Apellido = "Gómez",
                            Nombre = "Ana"
                        },
                        new
                        {
                            UsuID = 3m,
                            Apellido = "Martínez",
                            Nombre = "Luis"
                        },
                        new
                        {
                            UsuID = 4m,
                            Apellido = "López",
                            Nombre = "Marta"
                        },
                        new
                        {
                            UsuID = 5m,
                            Apellido = "Ramírez",
                            Nombre = "Carlos"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
